name: Deploy to ECR

on:
  pull_request:
    branches:
      - master
    types: [closed]  # Trigger only when the PR is closed (merged or rejected)

jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  # This ensures the workflow runs only when the PR is merged

    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1
        
    - name: Build, test, tag, and push image to Amazon ECR
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        MYSQL_ECR_REPOSITORY: mysql-repo
        MYSQL_IMAGE_TAG: v0.1
        WEBAPP_ECR_REPOSITORY: webapp-repo
        WEBAPP_IMAGE_TAG: v0.1
        
      run: |
        ls -ltra
        # Docker build command
        docker build -t $ECR_REGISTRY/$MYSQL_ECR_REPOSITORY:$IMAGE_TAG .
        docker build -t $ECR_REGISTRY/WEBAPP_ECR_REPOSITORY:$IMAGE_TAG .

        docker push $ECR_REGISTRY/$MYSQL_ECR_REPOSITORY:$IMAGE_TAG
        docker push $ECR_REGISTRY/$WEBAPP_ECR_REPOSITORY:$IMAGE_TAG