name: Deploy to ECR

on:
  pull_request:
    branches:
      - master
    types: [closed]  
jobs:
  build:
    name: Build Image
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true  
    
    steps:
    - name: Check out code
      uses: actions/checkout@v4

    - name: Build, test, tag, and push images to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
        AWS_REGION: us-east-1  
        
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        MYSQL_ECR_REPOSITORY: ${{ secrets.MYSQL_ECR_REPOSITORY }}
        MYSQL_IMAGE_TAG: ${{ secrets.MYSQL_IMAGE_TAG }}
        WEBAPP_ECR_REPOSITORY: ${{ secrets.WEBAPP_ECR_REPOSITORY }}
        WEBAPP_IMAGE_TAG: ${{ secrets.WEBAPP_IMAGE_TAG }}

      run: |
        
        echo "Building MySQL Image..."
        docker build -f Dockerfile_mysql -t $ECR_REGISTRY/$MYSQL_ECR_REPOSITORY:$MYSQL_IMAGE_TAG .

        echo "Building WebApp Image..."
        docker build -f Dockerfile -t $ECR_REGISTRY/$WEBAPP_ECR_REPOSITORY:$WEBAPP_IMAGE_TAG .

        echo "Pushing MySQL Image to ECR..."
        docker push $ECR_REGISTRY/$MYSQL_ECR_REPOSITORY:$MYSQL_IMAGE_TAG

        echo "Pushing WebApp Image to ECR..."
        docker push $ECR_REGISTRY/$WEBAPP_ECR_REPOSITORY:$WEBAPP_IMAGE_TAG
